---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'

- name: Enable 32 bit packages
  become: yes
  become_user: root
  when: winehq_enable_32bit_arch
  command: dpkg --add-architecture i386

- name: Add apt key to trust apt repo
  become: yes
  become_user: root
  get_url:
    url: '{{winehq_apt_key_url}}'
    dest: /usr/share/keyrings/winehq-archive.key
    owner: root
    group: root
    mode: '0600'

- name: Add apt repo
  become: yes
  become_user: root
  template:
    src: winehq.sources.j2
    dest: '/etc/apt/sources.list.d/winehq-{{ ansible_distribution_release }}.sources'
    owner: root
    group: root
    mode: '0600'

- name: Install winehq packages
  become: yes
  become_user: root
  apt:
    name: '{{winehq_pkgs}}'
    state: present
    update_cache: yes
    install_recommends: yes
